services:
  # === Database ===
  db:
    image: postgis/postgis:15-3.3
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # === Backend ===
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: php_backend
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: myapp
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db
    restart: always


  # === Dashboard Frontend ===
  dashboard_frontend:
    build: ./frontend/MuniciPAL-DashboardSite-main
    container_name: munici-pal-main-dashboard
    ports:
      - "3000:80"
    depends_on:
      - backend

  # === Ticket Log Frontend ===
  ticket_log_frontend:
    build: ./frontend/munici-pal-ticket-log
    container_name: munici-pal-ticket-log
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  db_data:
